#!/bin/bash
# Generate karma_core.c by extracting the DSP from the reference karma~.c and
# applying the Max -> core transforms. Re-run after touching the reference.
set -e
cd "$(dirname "$0")"
REF=../karma_tilde/karma~.c
OUT=karma_core.c
RAW=$(mktemp)

# print one C function: from line $1 until the first column-0 '}'
extract(){ awk -v s="$1" 'NR>=s{print} NR>=s && /^}/{exit}' "$REF"; }

{
  echo '// GENERATED by gen_core.sh from karma~.c -- do not edit by hand.'
  echo '#include "karma_core.h"'
  echo
  echo '// buffer-modify notification is a host concern; no-op in the core.'
  echo 'static void karma_buf_modify(t_karma *x, void *b) { (void)x; (void)b; }'
  echo
  echo '// ---- DSP helpers (verbatim from reference) ----'
  sed -n '236,434p' "$REF"
  echo
  echo '// ---- control methods (verbatim) ----'
  for L in 1427 1492 1533 1572 1584 1600 1707 1724 1743; do extract "$L"; echo; done
  echo '// ---- mono perform (verbatim) ----'
  extract 1842
  echo '// ---- stereo perform (verbatim) ----'
  extract 2914
  echo '// ---- quad perform (verbatim) ----'
  extract 4916
} > "$RAW"

# Max -> core transforms: buffer access via the host iface; drop the
# Max-disabled check. (clock_delay/clock_unset are no-op macros in the header.)
sed -E \
  -e 's/buffer_ref_getobject\(x->buf\)/x->bufio.ctx/g' \
  -e 's/buffer_locksamples\(buf\)/((float*)x->bufio.lock(x->bufio.ctx))/g' \
  -e 's/buffer_setdirty\(buf\)/x->bufio.set_dirty(x->bufio.ctx)/g' \
  -e 's/buffer_unlocksamples\(buf\)/x->bufio.unlock(x->bufio.ctx)/g' \
  -e 's/ \|\| x->k_ob\.z_disabled//g' \
  "$RAW" > "$OUT"

cat >> "$OUT" <<'EOF'

// ---- init / configure (mirrors karma_new defaults + karma_buf_setup) ----
void karma_core_init(t_karma *x, long ochans, double ssr, double vs)
{
    memset(x, 0, sizeof(*x));
    x->recordhead = -1;
    x->reportlist = 50;
    x->snrramp = x->globalramp = 256;
    x->playfade = x->recordfade = 257;
    x->ssr = ssr; x->vs = vs; x->vsnorm = (ssr > 0) ? (vs / ssr) : 0.0;
    x->overdubprev = x->overdubamp = x->speedfloat = 1.0;
    x->islooped = x->snrtype = x->interpflag = 1;
    x->initiallow = x->initialhigh = -1;
    x->ochans = (ochans <= 1) ? 1 : ((ochans == 2) ? 2 : 4);
    x->initskip = 1;
}

void karma_core_set_dims(t_karma *x)
{
    if (!x->bufio.ctx) return;
    x->directionorig = 0;
    x->maxhead = x->playhead = 0.0;
    x->recordhead = -1;
    x->bchans  = x->bufio.chans;
    x->bframes = x->bufio.frames;
    x->bmsr    = x->bufio.sr * 0.001;
    x->bsr     = x->bufio.sr;
    x->nchans  = (x->bchans < x->ochans) ? x->bchans : x->ochans;
    x->srscale = x->bsr / x->ssr;
    x->bvsnorm = x->vsnorm * (x->bsr / (double)x->bframes);
    x->minloop = x->startloop = 0.0;
    x->maxloop = x->endloop   = (x->bframes - 1);
    x->selstart  = 0.0;
    x->selection = 1.0;
}
EOF

rm -f "$RAW"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
